### ISSUE TITLE
asyncio.queues.QueueFull Error after X hours of running.

### ISSUE THREAD

**Issue by ThatKalle** [snstac/pytak#83]
Error message recieved after running without issue for 17hrs or so.
```bat
2024-10-26 15:17:37,904 pytak INFO - Complete: <Task finished name='Task-3' coro=<RXWorker.run() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python313-32\Lib\site-packages\pytak\classes.py:236> exception=QueueFull()>
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-3' coro=<RXWorker.run() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python313-32\Lib\site-packages\pytak\classes.py:236> exception=QueueFull()>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313-32\Lib\site-packages\pytak\classes.py", line 246, in run
    self.queue.put_nowait(data)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313-32\Lib\asyncio\queues.py", line 166, in put_nowait
    raise QueueFull
asyncio.queues.QueueFull

C:\adsbcot>
```

dump1090.exe still running.
TAK-server still running.

Results in CoTs no longer being sent to server.

A restart of the program enabled flow again `adsbcot -c adsbcot.ini`.

**Comment by ampledata** [comment]
adsbcot is expected to exit when it encounters these types of errors. You should run it as a daemon with a process management tool like systemd, supervisord, et al. I know Windows has a process manager for these types of things, but I'm not familiar enough with it to offer advice on setup.

**Comment by Zuilf456WQ** [comment]
Had the same issue, event when increasing the queue size in the file config. Any idea what cause that?

**Comment by kd2var** [comment]
Hi, I believe this issue may still be present. It was reported as fixed in PyTAK v7.3.9, but I am still seeing the same queue full / TX worker stall behavior in both v7.3.12 and v7.6.1.
The application keeps running, but the queue fills and COT output stops until PyTAK/ADSBCOT is restarted.
Has anyone found a workaround or confirmed whether this issue is fully resolved in the newer versions?
